export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FAILED = 'FAILED';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SAGA = 'PURCHASE_BURGER_SAGA';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export const FETCH_ORDERS_SAGA = 'FETCH_ORDERS_SAGA'; 
export const FETCH_INGREDIENTS_SAGA = 'FETCH_INGREDIENTS_SAGA';

export const CHECK_AUTH_TIMEOUT = 'CHECK_AUTH_TIMEOUT';
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';
export const AUTH_USER_SAGA = 'AUTH_USER_SAGA'; 
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const SAGA_LOGOUT = 'SAGA_LOGOUT';
export const LOG_OUT = 'LOG_OUT';

export const SET_AUTH_PATH = 'SET_AUTH_PATH';

